config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    post '/users/:id/follow', to: 'users/registrations#follow', as: 'user_follow'
  end

  resources :tweets
  post 'tweets/:id/like', to: 'tweets#like', as: 'tweet_like'
  post 'tweets/:id/retweet', to: 'tweets#retweet', as: 'tweet_retweet'

  root 'tweets#index'

  namespace :api do
    mount_devise_token_auth_for 'User', at: 'auth'
    get 'news', to: 'api#news'
    get ':date_from/:date_to', to: 'api#between', as: 'between'
    post 'create', to: 'api#create', as: 'create'
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :delete_all
  has_many :retweets, class_name: 'Tweet', foreign_key: :tweet_id, dependent: :delete_all
  belongs_to :original_tweet, class_name: 'Tweet', foreign_key: :tweet_id, optional: true

  validates :content, presence: true

  paginates_per 50

  def retweet(user)
    Tweet.create(original_tweet: self, content: 'Retweet', user: user)
  end

  def liked?(user)
    likes.where(user: user).size.positive?
  end

  def like(user)
    Like.create(user: user, tweet: self)
  end

  def unlike(user)
    likes.where(user: user).destroy_all
  end

  def toggle_like(user)
    if liked?(user)
      unlike(user)
    else
      like(user)
    end
  end

  def like_count
    likes ? likes.length : 0
  end

  def retweet_count
    retweets ? retweets.size : 0
  end

  scope :tweets_for_me, ->(user) { where(user: user.following_users) if user.present? }
  scope :retweets, -> { where.not(original_tweet: nil) }
  scope :news, -> { last(50) }
  scope :between, ->(date_from, date_to) { where(created_at: date_from..date_to) }
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[show update destroy retweet like]

  def format_tweet_content(content)
    content.gsub(/#\b\w+\b/) { |hashtag| "<a href=#{tweets_path}?q[content_cont]=%23#{hashtag[1..]}>#{hashtag}</a>" }
  end
  helper_method :format_tweet_content

  def index
    @q = Tweet.tweets_for_me(current_user).ransack(params[:q])
    @tweets = @q.result.order(id: :desc).page(params[:page])
  end

  def show
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: 'Tweet was successfully created.' }
      else
        format.html { redirect_to root_path, alert: 'Tweet could not be created.' }
      end
    end
  end

  def like
    @tweet.toggle_like(current_user)

    respond_to do |format|
      notice = "Tweet #{@tweet.liked?(current_user) ? 'liked' : 'unliked'}"
      format.js { render nothing: true, notice: notice }
      format.html { redirect_to root_path, notice: notice }
    end
  end

  def retweet
    new_tweet = @tweet.retweet(current_user)

    respond_to do |format|
      if new_tweet
        format.html { redirect_to root_path, notice: 'Retweeted!' }
      else
        format.html { redirect_to root_path, alert: 'Retweet not successful.' }
      end
    end
  end

  def update
  end

  def destroy
    @tweet.destroy

    respond_to do |format|
      notice = 'Tweet deleted.'
      format.js {render nothing: true, notice: notice }
      format.html { redirect_to root_path, notice: notice }
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:content)
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_tweet.html.erb
<div class="col col-tweet mb-4">
  <div class="card <%= local_assigns[:retweet] ? 'card-retweet' : 'card-tweet' %>">
    <div class="card-body">
      <div class="tweet-header">
        <img class="user-avatar" src="<%= tweet.user.pic_url %>" /> 
        <div class="tweet-header-left">
          <h5 class="card-title tweet-title">
            <%= tweet.user %>
          </h5><br>
          <small class="text-muted px-1"><%= fa_icon('heart', type: :solid) %> <%= tweet.like_count %></small>
          <small class="text-muted px-1"><%= fa_icon('share', type: :solid) %> <%= tweet.retweet_count %></small>
        </div>
        <% if signed_in? %>
          <% unless local_assigns[:retweet] %>
            <div class="tweet-button-group">
              <% if can? :destroy, tweet %>
                <%= link_to tweet_path(tweet), method: :delete, data: { confirm: 'Are you sure?' }, remote: true, class: "px-2", id: "tweet-delete-link-#{tweet.id}" do %>
                  <%= fa_icon('trash-alt', type: :solid) %>
                <% end %>
              <% end %>
              <%= link_to tweet_like_path(tweet), method: :post, remote: true, class: "px-2", id: "tweet-like-link-#{tweet.id}" do %>
                <%= tweet.liked?(current_user) ? fa_icon('heart', type: :solid) : fa_icon('heart', type: :regular) %>
              <% end %>
              <%= link_to tweet_retweet_path(tweet), method: :post, remote: true, class: "px-2" do %>
                <%= fa_icon('share', type: :solid) %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
      <p class="card-text"><%= raw format_tweet_content(tweet.content) %></p>
      <p class="card-text">
        <small class="text-muted">
          <%= link_to "#{time_ago_in_words(tweet.created_at)} ago", tweet_path(tweet) %>
        </small>
        <% if signed_in? && !local_assigns[:retweet] && can?(:follow, tweet.user) %>
          <small class="text-muted tweet-unfollow-link">
            <%= link_to(current_user.following?(tweet.user) ? 'Unfollow' : 'Follow', user_follow_path(tweet.user),
            method: :post, remote: true, class: "tweet-follow-link-#{tweet.user.id}") %>
          </small>
        <% end %>
      </p>
      <% if tweet.original_tweet %>
        <%= render tweet.original_tweet, retweet: true %>
      <% end %>
    </div>
  </div>
</div>

app/views/tweets/_tweet_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <div class="form-group">
    <%= form.text_area :content, placeholder: "Your message ...", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Tweet!", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tweets/_tweet_view.html.erb
<div class="col mb-4">
  <div class="card <%= retweet ? 'card-retweet' : 'card-tweet' %>">
    <div class="card-body">
      <div class="tweet-header">
        <img class="user-avatar" src="<%= tweet.user.pic_url %>" /> 
        <div class="tweet-header-left">
          <h5 class="card-title tweet-title">
            <%= tweet.user %>
          </h5><br>
          <small class="text-muted px-1"><%= fa_icon('heart', type: :solid) %> <%= tweet.like_count %></small>
          <small class="text-muted px-1"><%= fa_icon('share', type: :solid) %> <%= tweet.retweet_count %></small>
        </div>
        <% if signed_in? %>
          <% unless retweet %>
            <div class="tweet-button-group">
              <%= link_to tweet_like_path(tweet), method: :post, class: "px-2" do %>
                <%= tweet.liked?(current_user) ? fa_icon('heart', type: :solid) : fa_icon('heart', type: :regular) %>
              <% end %>
              <%= link_to tweet_retweet_path(tweet), method: :post, class: "px-2" do %>
                <%= fa_icon('share', type: :solid) %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
      <p class="card-text"><%= tweet.content %></p>
      <p class="card-text">
        <small class="text-muted">
          <%= link_to "#{time_ago_in_words(tweet.created_at)} ago", tweet_path(tweet) %>
        </small>
      </p>
      <% if tweet.original_tweet %>
        <%= render 'tweet_view', tweet: tweet.original_tweet, retweet: true %>
      <% end %>
    </div>
  </div>
</div>

app/views/tweets/destroy.js.erb
// remove user from "users to follow"
id = "#tweet-delete-link-<%= @tweet.id %>";
$(id).parentsUntil('.col-tweet').parent().hide(500);

app/views/tweets/index.html.erb
<% if signed_in? %>
  <div class="my-5">
    <%= render 'tweet_form', tweet: Tweet.new %>
  </div>
  <div class="users-to-follow-outer my-5">
    <h2 class="display-5 my-3">You might be interested in following these users</h2>
    <%= render "shared/users_to_follow" %>
  </div>
<% end %>

<div class="tweets-header-outer my-3">
  <span class="display-4">Tweets</span>
  <%= search_form_for @q, class: "form-inline search-bar" do |f| %>
    <%= f.search_field :content_cont, class: "form-control mr-2" %>
    <%= f.submit class: "btn btn-secondary" %>
  <% end %>
</div>
<% if @tweets.size.positive? %>
  <div class="row row-cols-1">
    <%= render(@tweets) %>
  </div>
<% else %>
  <h3>No tweets found :(</h3>
<% end %>

<div class="my-3">
  <%= paginate @tweets %>
</div>

app/views/tweets/like.js.erb
id = "#tweet-like-link-<%= @tweet.id %>"
elem = $(id).children();

<% if @tweet.liked?(current_user) %>
  elem.removeClass('far');
  elem.addClass('fas');
<% else %>
  elem.removeClass('fas');
  elem.addClass('far');
<% end %>

app/views/tweets/show.html.erb
<h1 class="display-3 my-3">Tweet</h1>

<%= render @tweet, retweet: false %>

<h2 class="display-4">Likes</h2>
<ul>
  <% @tweet.likes.each do |like| %>
    <li class="tweet-detail-li">
      <img class="user-avatar" src="<%= like.user.pic_url %>" title="<%= like.user %>" />
    </li>
  <% end %>
</ul>

app/views/tweets/update.html.erb
<h1>Tweets#update</h1>
<p>Find me in app/views/tweets/update.html.erb</p>