config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    post '/users/:id/follow', to: 'users/registrations#follow', as: 'user_follow'
  end

  resources :tweets
  post 'tweets/:id/like', to: 'tweets#like', as: 'tweet_like'
  post 'tweets/:id/retweet', to: 'tweets#retweet', as: 'tweet_retweet'

  root 'tweets#index'

  namespace :api do
    mount_devise_token_auth_for 'User', at: 'auth'
    get 'news', to: 'api#news'
    get ':date_from/:date_to', to: 'api#between', as: 'between'
    post 'create', to: 'api#create', as: 'create'
  end
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%= root_path %>">Zwitscher</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <% if signed_in? %>
        <li class="nav-item">
          <%= link_to current_user, edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, method: "delete", class: "btn btn-secondary" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class: "btn btn-primary" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to "Admin", admin_user_session_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_users_to_follow.html.erb
<div class="row row-cols-2 row-cols-lg-4 users-to-follow-inner">
  <% current_user.users_to_follow.each do |u| %>
    <div class="user-to-follow p-2">
      <img class="user-avatar" src="<%= u.pic_url %>" title="<%= u %>" />
      <div class="user-to-follow-header">
        <h5 class="user-to-follow-name"><%= u %></h5><br>
        <%= link_to(
          current_user.following?(u) ? 'Unfollow' : 'Follow', user_follow_path(u),
          remote: true, method: :post, class: "card-link user-follow-link-#{u.id}")
        %>
      </div>
    </div>
  <% end %>
</div>